using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Text.Json.Serialization;

namespace OpenAI.Services.Data
{
    public class CompletionResponseData
    {
        [JsonPropertyName("id")]
        public string? Id { get; set;}

        [JsonPropertyName("object")]
        [SuppressMessage("Naming", "CA1720:Identifier contains type name", Justification = "This is the name of the property returned by the API.")]
        public string? @Object { get; set;}

        [JsonPropertyName("created")]
        public int Created { get; set;}

        [JsonPropertyName("model")]
        public string? Model { get; set;}

        [JsonPropertyName("choices")]
        public List<OpenAIChoice>? Choices { get; set;}

        [JsonPropertyName("usage")]
        public OpenAIUsage? Usage { get; set;}

        [JsonPropertyName("service_tier")]
        public string? ServiceTier { get; set; }

        [JsonPropertyName("system_fingerprint")]
        public string? SystemFingerprint { get; set; }
    }

    /// <summary>
    /// Detailed breakdown of tokens used to process the completion request.
    /// </summary>
    public class OpenAIUsage
    {
        [JsonPropertyName("prompt_tokens")]
        public int PromptTokens { get; set; }

        [JsonPropertyName("completion_tokens")]
        public int CompletionTokens { get; set; }

        [JsonPropertyName("total_tokens")]
        public int TotalTokens { get; set; }

        [JsonPropertyName("prompt_tokens_details")]
        public PromptTokensDetails? PromptTokensDetails { get; set; }

        [JsonPropertyName("completion_tokens_details")]
        public CompletionTokensDetails? CompletionTokensDetails { get; set; }
    }

    public class PromptTokensDetails
    {
        [JsonPropertyName("cached_tokens")]
        public int? CachedTokens { get; set; }
        [JsonPropertyName("audio_tokens")]
        public int? AudioTokens { get; set; }
    }

    public class CompletionTokensDetails
    {
        [JsonPropertyName("reasoning_tokens")]
        public int? ReasoningTokens { get; set; }
        [JsonPropertyName("audio_tokens")]
        public int? AudioTokens { get; set; }
        [JsonPropertyName("accepted_prediction_tokens")]
        public int? AcceptedPredictionTokens { get; set; }
        [JsonPropertyName("rejected_prediction_tokens")]
        public int? RejectedPredictionTokens { get; set; }
    }

    [DebuggerDisplay("Text = {Text}")]
    public class OpenAIChoice
    {
        /// <summary>
        /// Completion text generated by the GPT API.
        /// </summary>
        /// <remarks>Returned text does not include the stop sequence.</remarks>
        [JsonPropertyName("message")]
        public ChoiceMessage? Message { get; set; }

        [JsonPropertyName("index")]
        public int Index { get; set; }

        [JsonPropertyName("logprobs")]
        public object? LogProbabilities { get; set; }

        [JsonPropertyName("finish_reason")]
        public string? FinishReason { get; set; }
    }

    public class ChoiceMessage
    {
        [JsonPropertyName("role")]
        public string? Role { get; set; }
        [JsonPropertyName("content")]
        public string? Content { get; set; }
        [JsonPropertyName("refusal")]
        public string? Refusal { get; set; }
    }
}
